### ISSUE TITLE
Test this package against all major supported versions

### ISSUE THREAD

**Issue by nbro** [dossan/tktable#12]
We probably need to use e.g. docker containers to test this.

### TODO

- [ ] Can we create a docker image with tcl and the original tcl's tktable?
- [ ] Can we use e.g. this https://github.com/wjoye/tktable to always make sure the original tcl's library is installed?
- [ ] Can we try to automatically install https://www.activestate.com/products/tcl/? At least, the error messages should be more descriptive.
